# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ca0e8231d1537dd96c3569adc6539beba2dd6579de4a00dd2228cb541c4a08cf9d953bb6761805954040cf224a84955f6baf9de711f39f7e28ef6e61936287

test:
  secret_key_base: f53f2894b855e4393fc9c96a006c7530f1f0518bef0fd4ee9324e004c7221f028fa367382e72738553c0878572e9e0b630f389b5d4f84af1c7aa62ecb0f8d047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
